name: Add issues and PRs to maintainer board

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  contents: read

jobs:
  add-to-project:
    name: Add to maintainer board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v2.0.0
        with:
          project-url: https://github.com/users/kisaragi-mochi/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
